require:
  - standard
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-rake

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  DisabledByDefault: true
  SuggestExtensions: false
  Exclude:
    - "**/tmp/**/*"
    - "**/vendor/**/*"
