require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-rake
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "**/tmp/**/*"
    - "**/vendor/**/*"
